# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 431178ee8d27a5515237e5025b58a79df8dfa90666a8782c10cf5a2541eb02516a75c01b512891c6c3effeba0b178903753353701e5c26dd7ebc4a1a27538748

test:
  secret_key_base: e0a9fe4c39d7e8779d07ddf16eba472dc61d16bf4dd965591931540a262d1416015d61337318341231adf90229d833751bbb3bbdf58c1e5cd287b8c585fd1336

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
